package light.mvc.utils;

import java.io.IOException;
import java.sql.SQLException;

import freemarker.template.TemplateException;

public class AutoGenerationDemo {

    public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException, TemplateException {
        //数据库地址
        String url = "jdbc:mysql://localhost:3306/demo";
        //用户名
        String name = "root";
        //密码
        String passWord = "root";
        //驱动
        String driver = "com.mysql.jdbc.Driver";
        //表名
        String tableName = "sys_role";
        //模板路径
        String templateDir = "F:\\template";
        //生成文件路径
        String autoGeneratedFile = "F:\\autoGenerated";
        //实例化
        AutoGenerationJavaCode autoGenerationJavaCode = new AutoGenerationJavaCode(url, name, passWord, driver,
                tableName,autoGeneratedFile,templateDir);
        
        //调用生成java代码方法
        autoGenerationJavaCode.autoGenerationJavaCode();
    }

}
